[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "timbre-transfer-ddsp"
version = "0.1.0"
description = "DDSP-based timbre transfer experiments"
readme = "README.md"
requires-python = "<3.11"

dependencies = [
    "pytimbre==1.0.2.2",
    "numpy",
    "pandas",
    "matplotlib",
    "ipykernel",
    "ddsp>=3.6.0",
    "scipy",
    "pyworld",
    "soundfile",
    "librosa",
    "apache-beam",
    "tensorflow==2.11.1",
    "tensorflow-probability==0.19.0",
    "frechet_audio_distance",
]

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = [
    "utils",
    "baseline",
    "data_preprocessing",
    "experiment_pipeline",
    "feature_utils",
    "model_loading",
    "timbre_transfer",
    "visualize",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["evaluation"]

